apiVersion: v1
kind: Service
metadata:
  name: srv-api
  namespace: dev
  labels:
    app: go-api
    project: my-k8s-infra
spec:
  selector:
    app: go-api
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP